### ISSUE TITLE
still working???

### ISSUE THREAD

**Issue by nk932714** [kletellier/pubg-replay#1]
i found nothing when i entered shroud on your demo site

**Comment by kletellier** [comment]
PUBG api only send last 14 days telemetry, it seems shroud doens't play during this period

**Comment by nk932714** [comment]
Thanks!
one more thing. Does this repo only display PC & Xbox players data ???

**Comment by kletellier** [comment]
regional shards are deprecated and replaced by pc,xbox,ps4 i need to implement them

**Comment by nk932714** [comment]
Thanks a lot buddy, working fine :+1:
